# .streamlit/secrets.toml
# This file should be created in your Streamlit Cloud deployment settings

# Email Configuration (Gmail example)
smtp_server = "smtp.gmail.com"
smtp_port = 587
email_address = "your-email@gmail.com"
email_password = "your-app-password"  # Use App Password for Gmail

# Twilio Configuration
twilio_account_sid = "your-twilio-account-sid"
twilio_auth_token = "your-twilio-auth-token"
twilio_phone = "+1234567890"  # Your Twilio phone number